name: nix

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v13
        with:
          # Got hash from https://github.com/cachix/install-nix-action/issues/83
          install_url: https://nixos-nix-install-tests.cachix.org/serve/pqndq1i9g5agiyr5iwwyl061s1c71kl6/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Check
        run: nix flake check

      - name: Test cabal-fmt
        run: nix run .#cabal-fmt -- --help

      - name: Test fourmolu
        run: nix run .#fourmolu -- --help

      - name: Test hlint
        run: nix run .#hlint -- --help

      - name: Test haddock coverage
        run: nix run .#haddock-cov -- --nh-help

      # for some reason, 'nix run .#nixpkgs-fmt -- --help' dies on ci
      - name: Test nixpkgs-fmt
        run: nix run .#nixpkgs-fmt

      - name: Test ormolu
        run: nix run .#ormolu -- --help

      - name: Test stylish
        run: nix run .#stylish -- --help

      - name: Test help
        run: nix run .#help

      - name: Test version
        run: nix run .#version
