name: nix

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: nix flake check

      - name: Test cabal-fmt
        run: nix run .#cabal-fmt -- --help

      - name: Test fourmolu
        run: nix run .#fourmolu -- --help

      - name: Test hlint
        run: nix run .#hlint -- --help

      - name: Test haddock coverage
        run: nix run .#haddock-cov -- --nh-help

      # for some reason, 'nix run .#nixpkgs-fmt -- --help' dies on ci
      - name: Test nixpkgs-fmt
        run: nix run .#nixpkgs-fmt

      - name: Test ormolu
        run: nix run .#ormolu -- --help

      - name: Test stylish
        run: nix run .#stylish -- --help

      - name: Test help
        run: nix run .#help

      - name: Test version
        run: nix run .#version
